language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    - develop

before_install:
  - chmod +x ./gradlew
  - ./gradlew setupWorkspace

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'

script: './gradlew clean test'