language: java
jdk: openjdk8
branches:
  only:
    - master
    - legacy-jdk8

before_install:
  - chmod +x ./gradlew

install:
  - ./gradlew setupWorkspace

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

script:
  - ./gradlew clean test