language: java
jdk: openjdk16
branches:
  only:
    - master

before_install:
  - chmod +x ./gradlew

install:
  - ./gradlew setupWorkspace

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

script:
  - ./gradlew clean test