name: $pluginName
version: $pluginVersion
main: $pluginMain
depend: [ProtocolLib]
author: Noonmaru
api-version: '1.13'
commands:
  tap:
    usage: /<command> help
    description: TapLoader plugin test command